# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Sat May  4 20:50:28 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainFrame(object):
    def setupUi(self, MainFrame):
        MainFrame.setObjectName("MainFrame")
        MainFrame.setWindowModality(QtCore.Qt.NonModal)
        MainFrame.resize(771, 431)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFrame.sizePolicy().hasHeightForWidth())
        MainFrame.setSizePolicy(sizePolicy)
        MainFrame.setStatusTip("")
        MainFrame.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainFrame)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setMouseTracking(True)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listWidget.setLineWidth(0)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setAutoScroll(False)
        self.listWidget.setTabKeyNavigation(True)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setDragEnabled(False)
        self.listWidget.setDragDropOverwriteMode(False)
        self.listWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.listWidget.setIconSize(QtCore.QSize(200, 200))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setFlow(QtGui.QListView.LeftToRight)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setResizeMode(QtGui.QListView.Fixed)
        self.listWidget.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget.setSpacing(3)
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setWordWrap(True)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DialSlideDur = QtGui.QDial(self.horizontalWidget)
        self.DialSlideDur.setMouseTracking(False)
        self.DialSlideDur.setStatusTip("")
        self.DialSlideDur.setWhatsThis("")
        self.DialSlideDur.setAccessibleName("")
        self.DialSlideDur.setAccessibleDescription("")
        self.DialSlideDur.setAutoFillBackground(False)
        self.DialSlideDur.setInputMethodHints(QtCore.Qt.ImhNone)
        self.DialSlideDur.setMinimum(1)
        self.DialSlideDur.setMaximum(1000)
        self.DialSlideDur.setProperty("value", 300)
        self.DialSlideDur.setSliderPosition(300)
        self.DialSlideDur.setInvertedAppearance(False)
        self.DialSlideDur.setInvertedControls(False)
        self.DialSlideDur.setWrapping(True)
        self.DialSlideDur.setNotchesVisible(True)
        self.DialSlideDur.setObjectName("DialSlideDur")
        self.horizontalLayout_3.addWidget(self.DialSlideDur)
        self.labSlideDur = QtGui.QLabel(self.horizontalWidget)
        self.labSlideDur.setObjectName("labSlideDur")
        self.horizontalLayout_3.addWidget(self.labSlideDur)
        self.btnPreview = QtGui.QCommandLinkButton(self.horizontalWidget)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout_3.addWidget(self.btnPreview)
        self.DialTransDur = QtGui.QDial(self.horizontalWidget)
        self.DialTransDur.setMinimum(1)
        self.DialTransDur.setMaximum(100)
        self.DialTransDur.setSingleStep(1)
        self.DialTransDur.setPageStep(10)
        self.DialTransDur.setProperty("value", 1)
        self.DialTransDur.setWrapping(True)
        self.DialTransDur.setNotchesVisible(True)
        self.DialTransDur.setObjectName("DialTransDur")
        self.horizontalLayout_3.addWidget(self.DialTransDur)
        self.labTransDur = QtGui.QLabel(self.horizontalWidget)
        self.labTransDur.setScaledContents(False)
        self.labTransDur.setOpenExternalLinks(False)
        self.labTransDur.setObjectName("labTransDur")
        self.horizontalLayout_3.addWidget(self.labTransDur)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddSlide = QtGui.QCommandLinkButton(self.centralwidget)
        self.btnAddSlide.setObjectName("btnAddSlide")
        self.horizontalLayout.addWidget(self.btnAddSlide)
        self.lcdPictures = QtGui.QLCDNumber(self.centralwidget)
        self.lcdPictures.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdPictures.setAutoFillBackground(False)
        self.lcdPictures.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdPictures.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdPictures.setLineWidth(0)
        self.lcdPictures.setSmallDecimalPoint(True)
        self.lcdPictures.setDigitCount(5)
        self.lcdPictures.setMode(QtGui.QLCDNumber.Dec)
        self.lcdPictures.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdPictures.setProperty("intValue", 0)
        self.lcdPictures.setObjectName("lcdPictures")
        self.horizontalLayout.addWidget(self.lcdPictures)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btnDelSlide = QtGui.QCommandLinkButton(self.centralwidget)
        self.btnDelSlide.setObjectName("btnDelSlide")
        self.horizontalLayout.addWidget(self.btnDelSlide)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboxPlugin = QtGui.QComboBox(self.centralwidget)
        self.comboxPlugin.setObjectName("comboxPlugin")
        self.comboxPlugin.addItem("")
        self.comboxPlugin.setItemText(0, "")
        self.comboxPlugin.addItem("")
        self.horizontalLayout_5.addWidget(self.comboxPlugin)
        self.btnSure = QtGui.QPushButton(self.centralwidget)
        self.btnSure.setToolTip("")
        self.btnSure.setStatusTip("None")
        self.btnSure.setObjectName("btnSure")
        self.horizontalLayout_5.addWidget(self.btnSure)
        self.comboxDiandian = QtGui.QComboBox(self.centralwidget)
        self.comboxDiandian.setObjectName("comboxDiandian")
        self.comboxDiandian.addItem("")
        self.comboxDiandian.setItemText(0, "")
        self.comboxDiandian.addItem("")
        self.comboxDiandian.addItem("")
        self.horizontalLayout_5.addWidget(self.comboxDiandian)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainFrame.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainFrame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 23))
        self.menubar.setObjectName("menubar")
        self.menuHELP = QtGui.QMenu(self.menubar)
        self.menuHELP.setObjectName("menuHELP")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainFrame.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainFrame)
        self.statusbar.setObjectName("statusbar")
        MainFrame.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainFrame)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDiandian = QtGui.QAction(MainFrame)
        self.actionDiandian.setIconVisibleInMenu(False)
        self.actionDiandian.setObjectName("actionDiandian")
        self.actionEmail = QtGui.QAction(MainFrame)
        self.actionEmail.setObjectName("actionEmail")
        self.actionKeybord = QtGui.QAction(MainFrame)
        self.actionKeybord.setObjectName("actionKeybord")
        self.actionOpen = QtGui.QAction(MainFrame)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_XML = QtGui.QAction(MainFrame)
        self.actionSave_XML.setObjectName("actionSave_XML")
        self.actionExit = QtGui.QAction(MainFrame)
        self.actionExit.setObjectName("actionExit")
        self.actionContent = QtGui.QAction(MainFrame)
        self.actionContent.setObjectName("actionContent")
        self.actionRefresh = QtGui.QAction(MainFrame)
        self.actionRefresh.setObjectName("actionRefresh")
        self.menuHELP.addAction(self.actionAbout)
        self.menuHELP.addAction(self.actionContent)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHELP.menuAction())

        self.retranslateUi(MainFrame)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainFrame)

    def retranslateUi(self, MainFrame):
        MainFrame.setWindowTitle(QtGui.QApplication.translate("MainFrame", "Gwaller", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setToolTip(QtGui.QApplication.translate("MainFrame", "Pictures listed here", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(True)
        self.DialSlideDur.setToolTip(QtGui.QApplication.translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aaaa00;\">Slide Duration (</span><span style=\" font-weight:600; color:#aaaa00;\">s</span><span style=\" color:#aaaa00;\">)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labSlideDur.setText(QtGui.QApplication.translate("MainFrame", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreview.setText(QtGui.QApplication.translate("MainFrame", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.DialTransDur.setToolTip(QtGui.QApplication.translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aa5500;\">Transision Duration (</span><span style=\" font-weight:600; color:#aa5500;\">s</span><span style=\" color:#aa5500;\">)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labTransDur.setText(QtGui.QApplication.translate("MainFrame", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSlide.setText(QtGui.QApplication.translate("MainFrame", "Add slide", None, QtGui.QApplication.UnicodeUTF8))
        self.lcdPictures.setToolTip(QtGui.QApplication.translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">How many pictures added into</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelSlide.setText(QtGui.QApplication.translate("MainFrame", "Del Slide", None, QtGui.QApplication.UnicodeUTF8))
        self.comboxPlugin.setToolTip(QtGui.QApplication.translate("MainFrame", "Picture from network", None, QtGui.QApplication.UnicodeUTF8))
        self.comboxPlugin.setItemText(1, QtGui.QApplication.translate("MainFrame", "Bing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSure.setText(QtGui.QApplication.translate("MainFrame", "Sure", None, QtGui.QApplication.UnicodeUTF8))
        self.comboxDiandian.setToolTip(QtGui.QApplication.translate("MainFrame", "Share your pictures to diandian, then you can set sync to other SNS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboxDiandian.setItemText(1, QtGui.QApplication.translate("MainFrame", "Post Link to diandian", None, QtGui.QApplication.UnicodeUTF8))
        self.comboxDiandian.setItemText(2, QtGui.QApplication.translate("MainFrame", "Post QRcode to diandian", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHELP.setTitle(QtGui.QApplication.translate("MainFrame", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainFrame", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainFrame", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiandian.setText(QtGui.QApplication.translate("MainFrame", "Diandian", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEmail.setText(QtGui.QApplication.translate("MainFrame", "email", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeybord.setText(QtGui.QApplication.translate("MainFrame", "Keybord", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainFrame", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainFrame", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_XML.setText(QtGui.QApplication.translate("MainFrame", "Save XML", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_XML.setShortcut(QtGui.QApplication.translate("MainFrame", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainFrame", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainFrame", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContent.setText(QtGui.QApplication.translate("MainFrame", "content", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContent.setShortcut(QtGui.QApplication.translate("MainFrame", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("MainFrame", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setShortcut(QtGui.QApplication.translate("MainFrame", "F5", None, QtGui.QApplication.UnicodeUTF8))

